name: Build, Test and Deploy Library App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Change the backend to localhost
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start the Backend
      run: npm run server &
    - name: Start the Frontend
      run: npm run start & 
    - name: Execute UI tests
      run: npm run test
